apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-first
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: example-ui
  template:
    metadata:
      labels:
        app: example-ui
        studies: first
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
